version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: webprobe_metrics

  app:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: webprobe_metrics
      CORS_ORIGIN: "*"
      NODE_ENV: production
    command: node server.js
    # No volume mount — source code baked into image

volumes:
  mongo-data:
